// frontend/vite/api-request-samples/projects/vue-sample/src/App.vue
<script setup lang="ts">
import useSWRV from "swrv";
import { getPokeAPIUrl, fetcher } from "constants";

const { data, error } = useSWRV(getPokeAPIUrl(1000), fetcher);
</script>

<template>
  <div>
    <h1>Hello, Vue</h1>
    <div v-if="error">failed to load</div>
    <div v-if="!data">loading...</div>
    <div v-else>
      <h2>{{ data.name }}</h2>
      <img :src="data.sprites.front_default" :alt="data.name" />
    </div>
  </div>
</template>

<style scoped></style>

// frontend/vite/api-request-samples/projects/solid-sample/src/App.tsx
import { createResource } from "solid-js";
import { getPokeAPIUrl, fetcher } from "constants";

function App() {
  const [data] = createResource(getPokeAPIUrl(1000), fetcher);

  return (
    <>
      <h1>Hello, Solid</h1>
      {data.error && <div>failed to load</div>}
      {data.loading && <div>loading...</div>}
      {data() && (
        <>
          <h2>{data()!.name}</h2>
          <img src={data()!.sprites.front_default} alt={data()!.name} />
        </>
      )}
    </>
  );
}

export default App;
