// frontend/vite/api-request-samples/projects/solid-sample/src/App.tsx
import { createResource } from "solid-js";
import { getPokeAPIUrl, fetcher } from "constants";

function App() {
  const [data] = createResource(getPokeAPIUrl(1000), fetcher);

  return (
    <>
      <h1>Hello, Solid</h1>
      {data.error && <div>failed to load</div>}
      {data.loading && <div>loading...</div>}
      {data() && (
        <>
          <h2>{data()!.name}</h2>
          <img src={data()!.sprites.front_default} alt={data()!.name} />
        </>
      )}
    </>
  );
}

export default App;

// frontend/vite/api-request-samples/projects/react-sample/src/App.tsx
import { getPokeAPIUrl, fetcher } from "constants";
import useSWR from "swr";

function App() {
  const { data, error, isLoading } = useSWR(getPokeAPIUrl(1000), fetcher);

  return (
    <>
      <h1>Hello, React</h1>
      <div>
        {error && <div>failed to load</div>}
        {isLoading && <div>loading...</div>}
        {data && (
          <>
            <h2>{data.name}</h2>
            <img src={data.sprites.front_default} alt={data.name} />
          </>
        )}
      </div>
    </>
  );
}

export default App;
