// frontend/vite/api-request-samples/projects/svelte-sample/src/App.svelte
<script lang="ts">
import {getPokeAPIUrl, fetcher} from "constants"

const fetchPokemon = fetcher(getPokeAPIUrl(1000))
</script>

<main>
  <h1>Hello, Svelte</h1>

  {#await fetchPokemon}
	  <p>loading...</p>
  {:then data}
    <h2>{data.name}</h2>
	  <img src={data.sprites.front_default} alt={data.name} />
  {:catch error}
	  <p>filed to load</p>
  {/await}
</main>

<style>
</style>

// frontend/vite/api-request-samples/projects/vue-sample/src/App.vue
<script setup lang="ts">
import useSWRV from "swrv";
import { getPokeAPIUrl, fetcher } from "constants";

const { data, error } = useSWRV(getPokeAPIUrl(1000), fetcher);
</script>

<template>
  <div>
    <h1>Hello, Vue</h1>
    <div v-if="error">failed to load</div>
    <div v-if="!data">loading...</div>
    <div v-else>
      <h2>{{ data.name }}</h2>
      <img :src="data.sprites.front_default" :alt="data.name" />
    </div>
  </div>
</template>

<style scoped></style>
